from pygame.color import THECOLORS

# Color
BLACK = THECOLORS["black"]

# Window
FPS = 30
WIN_HEIGHT = 600
WIN_WIDTH = 800
WIN_SIZE = (WIN_WIDTH, WIN_HEIGHT)
CAPTION = 'Brids In Rage'
ORIGIN = (0, 0)

# Birds
BIRD_HEIGHT = 48
BIRD_WIDTH = 48
BIRD_SIZE = (BIRD_WIDTH, BIRD_HEIGHT)

# Pigs
PIG_HEIGHT = 48
PIG_WIDTH = 48
PIG_SIZE = (PIG_WIDTH, PIG_HEIGHT)
