from pygame.color import THECOLORS

FPS = 30

# Color
BLACK = THECOLORS["black"]

# Window
WIN_HEIGHT = 600
WIN_WIDTH = 1000
WIN_SIZE = (WIN_WIDTH, WIN_HEIGHT)
WIN_BOTTOM = WIN_HEIGHT - 10

CAPTION = 'Brids In Rage'
ORIGIN = (0, 0)

# Object
OBJ_SIZE = 32
OBJ_BOTTOM = WIN_BOTTOM - OBJ_SIZE

# Birds
BIRD_HEIGHT = 32
BIRD_WIDTH = 32
BIRD_SIZE = (BIRD_WIDTH, BIRD_HEIGHT)

# Pigs
PIG_HEIGHT = 48
PIG_WIDTH = 48
PIG_SIZE = (PIG_WIDTH, PIG_HEIGHT)
